.\" $Id: shadowconfig.8,v 1.3 2001/08/23 23:10:51 kloczek Exp $
.\" {PTM/WK/1999-09-14}
.TH SHADOWCONFIG 8 "19 kwietnia 1997" "Debian GNU/Linux"
.\" http://bugs.debian.org/507673
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" http://bugs.debian.org/507673
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.SH NAZWA
shadowconfig - przełącza ochronę haseł i grup przez pliki shadow
.SH SKŁADNIA
.B "shadowconfig"
.IR on " | " off
.SH OPIS
.PP
.B shadowconfig on
włącza ochronę haseł i grup przez dodatkowe, przesłaniane pliki (shadow);
.B shadowconfig off
wyłącza dodatkowe pliki haseł i grup.
.B shadowconfig
wyświetla komunikat o błędzie i kończy pracę z niezerowym kodem jeśli
znajdzie coś nieprawidłowego. W takim wypadku powinieneś poprawić błąd
.\" if it finds anything awry.
i uruchomić program ponownie.

Włączenie ochrony haseł, gdy jest ona już włączona lub jej wyłączenie,
gdy jest wyłączona jest nieszkodliwe.

Przeczytaj
.IR /usr/share/doc/passwd/README.debian.gz ,
gdzie znajdziesz krótkie wprowadzenie do ochrony haseł z użyciem dodatkowych
plików haseł przesłanianych (shadow passwords) i związanych tematów.
