'\" t
.\"     Title: login
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 01/27/2016
.\"    Manual: Пользовательские команды
.\"    Source: Пользовательские команды
.\"  Language: Russian
.\"
.TH "login" "1" "01/27/2016" "Пользовательские команды" "Пользовательские команды"
.\" http://bugs.debian.org/507673
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" http://bugs.debian.org/507673
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "ИМЯ"
login \- начинает сеанс в системе
.SH "СИНОПСИС"
.HP \w'\fBlogin\fR\ 'u
\fBlogin\fR [\-p] [\-h\ \fIхост\fR] [\fIимя_пользователя\fR] [\fIПЕРЕМЕННАЯ_СРЕДЫ=ЗНАЧЕНИЕ\fR...]
.HP \w'\fBlogin\fR\ 'u
\fBlogin\fR [\-p] [\-h\ \fIхост\fR] \-f \fIимя_пользователя\fR
.HP \w'\fBlogin\fR\ 'u
\fBlogin\fR [\-p] \-r\ \fIхост\fR
.SH "ОПИСАНИЕ"
.PP
The
\fBlogin\fR
program is used to establish a new session with the system\&. It is normally invoked automatically by responding to the
\fIlogin:\fR
prompt on the user\*(Aqs terminal\&.
\fBlogin\fR
may be special to the shell and may not be invoked as a sub\-process\&. When called from a shell,
\fBlogin\fR
should be executed as
\fBexec login\fR
which will cause the user to exit from the current shell (and thus will prevent the new logged in user to return to the session of the caller)\&. Attempting to execute
\fBlogin\fR
from any shell but the login shell will produce an error message\&.
.PP
В какой\-то момент пользователя попросят ввести свой пароль\&. Чтобы недопустить раскрытия, символы при вводе пароля не отображаются\&. Разрешено очень маленькое число попыток ввода неправильного пароля, перед тем как
\fBlogin\fR
закончит работу и прервёт подключение\&.
.PP
Если включён механизм устаревания пароля учётной записи, то перед входом в систему может потребоваться смена пароля\&. Для этого нужно ввести старый пароль и новый пароль\&. Подробней об этом написано в
\fBpasswd\fR(1)\&.
.PP
Значения идентификатора учётной записи и группы будет взято из файла
/etc/passwd\&. Значения переменных
\fB$HOME\fR,
\fB$SHELL\fR,
\fB$PATH\fR,
\fB$LOGNAME\fR
и
\fB$MAIL\fR
устанавливаются согласно соответствующим полям учётной записи пользователя\&. Также могут быть установлены значения ulimit, umask и nice из поля GECOS\&.
.PP
В некоторых системах переменной среды
\fB$TERM\fR
будет присвоен тип терминала линии tty, согласно данным из файла
/etc/ttytype\&.
.PP
Также может быть выполнен сценарий инициализации пользовательского интерпретатора команд\&. Подробней об этой функции смотрите соответствующую страницу руководства\&.
.PP
Субсистемный вход в систему можно распознать по наличию символа "*" в начале регистрационной оболочки\&. Заданный домашний каталог будет использован как корень новой файловой системы, в которой регистрируется пользователь\&.
.PP
Программа
\fBlogin\fR
НЕ удаляет записи о пользователях из файла utmp\&. Эта задача программ
\fBgetty\fR(8)
и
\fBinit\fR(8)
удалять записи о владельце терминального сеанса\&. Если
\fBlogin\fR
запускается из командной строки без
\fBexec\fR, то пользователь продолжает находиться в системе даже после завершения работы в "порождённом сеансе"\&.
.SH "ПАРАМЕТРЫ"
.PP
\fB\-f\fR
.RS 4
Не выполнять аутентификацию, пользователь уже прошёл проверку\&.
.sp
Note: In that case,
\fIusername\fR
is mandatory\&.
.RE
.PP
\fB\-h\fR
.RS 4
Имя удалённого хоста, на который нужно войти\&.
.RE
.PP
\fB\-p\fR
.RS 4
Сохранить среду\&.
.RE
.PP
\fB\-r\fR
.RS 4
Выполнить протокол autologin для rlogin\&.
.RE
.PP
Параметры
\fB\-r\fR,
\fB\-h\fR
и
\fB\-f\fR
используются только если
\fBlogin\fR
запускается суперпользователем\&.
.SH "ПРЕДОСТЕРЕЖЕНИЯ"
.PP
Данная версия
\fBlogin\fR
может быть собрана с разными параметрами и только некоторые из них смогут быть использованы на любой машине\&.
.PP
Расположение файлов может отличаться на разных системах\&.
.PP
Программа
\fBlogin\fR
НЕ удаляет записи о пользователях из файла utmp\&. Эта задача программ
\fBgetty\fR(8)
и
\fBinit\fR(8)
удалять записи о владельце терминального сеанса\&. Если
\fBlogin\fR
запускается из командной строки без
\fBexec\fR, то пользователь продолжает находиться в системе даже после завершения работы в "порождённом сеансе"\&.
.PP
As with any program,
\fBlogin\fR\*(Aqs appearance can be faked\&. If non\-trusted users have physical access to a machine, an attacker could use this to obtain the password of the next person coming to sit in front of the machine\&. Under Linux, the SAK mechanism can be used by users to initiate a trusted path and prevent this kind of attack\&.
.SH "CONFIGURATION"
.PP
The following configuration variables in
/etc/login\&.defs
change the behavior of this tool:
.PP
\fBCONSOLE_GROUPS\fR (string)
.RS 4
List of groups to add to the user\*(Aqs supplementary groups set when logging in on the console (as determined by the CONSOLE setting)\&. Default is none\&.

Use with caution \- it is possible for users to gain permanent access to these groups, even when not logged in on the console\&.
.RE
.PP
\fBDEFAULT_HOME\fR (boolean)
.RS 4
Indicate if login is allowed if we can\*(Aqt cd to the home directory\&. Default in no\&.
.sp
If set to
\fIyes\fR, the user will login in the root (/) directory if it is not possible to cd to her home directory\&.
.RE
.PP
\fBENV_PATH\fR (string)
.RS 4
If set, it will be used to define the PATH environment variable when a regular user login\&. The value can be preceded by
\fIPATH=\fR, or a colon separated list of paths (for example
\fI/bin:/usr/bin\fR)\&. The default value is
\fIPATH=/bin:/usr/bin\fR\&.
.RE
.PP
\fBENV_SUPATH\fR (string)
.RS 4
If set, it will be used to define the PATH environment variable when the superuser login\&. The value can be preceded by
\fIPATH=\fR, or a colon separated list of paths (for example
\fI/sbin:/bin:/usr/sbin:/usr/bin\fR)\&. The default value is
\fIPATH=/sbin:/bin:/usr/sbin:/usr/bin\fR\&.
.RE
.PP
\fBERASECHAR\fR (number)
.RS 4
Terminal ERASE character (\fI010\fR
= backspace,
\fI0177\fR
= DEL)\&.
.sp
The value can be prefixed "0" for an octal value, or "0x" for an hexadecimal value\&.
.RE
.PP
\fBFAIL_DELAY\fR (number)
.RS 4
Delay in seconds before being allowed another attempt after a login failure\&.
.RE
.PP
\fBFAKE_SHELL\fR (string)
.RS 4
If set,
\fBlogin\fR
will execute this shell instead of the users\*(Aq shell specified in
/etc/passwd\&.
.RE
.PP
\fBHUSHLOGIN_FILE\fR (string)
.RS 4
If defined, this file can inhibit all the usual chatter during the login sequence\&. If a full pathname is specified, then hushed mode will be enabled if the user\*(Aqs name or shell are found in the file\&. If not a full pathname, then hushed mode will be enabled if the file exists in the user\*(Aqs home directory\&.
.RE
.PP
\fBKILLCHAR\fR (number)
.RS 4
Terminal KILL character (\fI025\fR
= CTRL/U)\&.
.sp
The value can be prefixed "0" for an octal value, or "0x" for an hexadecimal value\&.
.RE
.PP
\fBLOGIN_RETRIES\fR (number)
.RS 4
Maximum number of login retries in case of bad password\&.
.sp
This will most likely be overridden by PAM, since the default pam_unix module has it\*(Aqs own built in of 3 retries\&. However, this is a safe fallback in case you are using an authentication module that does not enforce PAM_MAXTRIES\&.
.RE
.PP
\fBLOGIN_TIMEOUT\fR (number)
.RS 4
Max time in seconds for login\&.
.RE
.PP
\fBLOG_OK_LOGINS\fR (boolean)
.RS 4
Enable logging of successful logins\&.
.RE
.PP
\fBLOG_UNKFAIL_ENAB\fR (boolean)
.RS 4
Enable display of unknown usernames when login failures are recorded\&.
.sp
Note: logging unknown usernames may be a security issue if an user enter her password instead of her login name\&.
.RE
.PP
\fBTTYGROUP\fR (string), \fBTTYPERM\fR (string)
.RS 4
The terminal permissions: the login tty will be owned by the
\fBTTYGROUP\fR
group, and the permissions will be set to
\fBTTYPERM\fR\&.
.sp
By default, the ownership of the terminal is set to the user\*(Aqs primary group and the permissions are set to
\fI0600\fR\&.
.sp

\fBTTYGROUP\fR
can be either the name of a group or a numeric group identifier\&.
.sp
If you have a
\fBwrite\fR
program which is "setgid" to a special group which owns the terminals, define TTYGROUP to the group number and TTYPERM to 0620\&. Otherwise leave TTYGROUP commented out and assign TTYPERM to either 622 or 600\&.
.RE
.PP
\fBTTYTYPE_FILE\fR (string)
.RS 4
If defined, file which maps tty line to TERM environment parameter\&. Each line of the file is in a format something like "vt100 tty01"\&.
.RE
.PP
\fBUSERGROUPS_ENAB\fR (boolean)
.RS 4
If set to
\fIyes\fR,
\fBuserdel\fR
will remove the user\*(Aqs group if it contains no more members, and
\fBuseradd\fR
will create by default a group with the name of the user\&.
.RE
.SH "ФАЙЛЫ"
.PP
/var/run/utmp
.RS 4
содержит список работающих сеансов в системе
.RE
.PP
/var/log/wtmp
.RS 4
содержит список завершённых сеансов работы с системой
.RE
.PP
/etc/passwd
.RS 4
содержит информацию о пользователях
.RE
.PP
/etc/shadow
.RS 4
содержит защищаемую информацию о пользователях
.RE
.PP
/etc/motd
.RS 4
содержит системные сообщения за день
.RE
.PP
/etc/nologin
.RS 4
при существовании файла блокируется доступ в систему обычным пользователям
.RE
.PP
/etc/ttytype
.RS 4
содержит список типов терминалов
.RE
.PP
$HOME/\&.hushlogin
.RS 4
при существовании файла системные сообщения при входе в систему не выводятся
.RE
.PP
/etc/login\&.defs
.RS 4
содержит конфигурацию подсистемы теневых паролей
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBmail\fR(1),
\fBpasswd\fR(1),
\fBsh\fR(1),
\fBsu\fR(1),
\fBlogin.defs\fR(5),
\fBnologin\fR(5),
\fBpasswd\fR(5),
\fBsecuretty\fR(5),
\fBgetty\fR(8)\&.
